### PR TITLE
Master

### PR DESCRIPTION
**Pull request by pablosproject**
Added tests to Pompeu sample project

### CODE REVIEW

**Comment by vilanovi** [comment]
Thanks Paolo!!

**Comment by pablosproject** [comment]
👍👍👍

**Comment by vilanovi** [comment]
I also added Travis support and upgraded the tag 0.1.0 to the latest version (you would probably have to delete your local 0.1.0 tag before pulling again).

**Comment by pablosproject** [comment]
Yep! I see travis is failing. I think that you've to share all the schemes in order to make it work.

**Comment by vilanovi** [comment]
Yes, did the changes now.

**Comment by pablosproject** [comment]
😎

**Comment by vilanovi** [comment]
After adding the shared scheme it is still failing. :/ don't really understand why. Any idea?

**Comment by vilanovi** [comment]
Here the log: https://api.travis-ci.org/jobs/65386294/log.txt?deansi=true

**Comment by pablosproject** [comment]
I think that this is the problem:
_dyld: app was built for iOS 8.3 which is newer than this simulator 8.1_

Maybe we can downgrade the simulator support.

The deploy target is 8.3, let's try to put it to 8.1.

**Comment by vilanovi** [comment]
Oh, of course. Didn't see that.

**Comment by pablosproject** [comment]
Now it's working!

**Comment by pablosproject** [comment]
The badge in the README file is not updated, I don't know if it's a bug of if a due to the refresh time of the badge.

**Comment by vilanovi** [comment]
I'd say its a bug on their side. The build is passing tests on travis website.

**Comment by vilanovi** [comment]
btw, what do you think about the library? do you think it is useful? do you use any other options?

**Comment by pablosproject** [comment]
Yes, absolutely! 
Actually I'm manually setting every string from the controller, because using Storyboards/XIB localization is a pain: every time you modify your xib you've to re-generate all the strings.
This is a more automated way.
Maybe we can add a base view controller that automatically calls the localization primitive. In this way can go straight-on the development.

**Comment by vilanovi** [comment]
We have been thinking on this (creating a UIViewController subclass) that already does the job. However, this is too agressive in terms of conditioning the user to use our "superclass" of viewcontroller instead of another one (ex: google analytics view controller or just some UIViewController from a cocoa pod). Therefore we decided to not do it. 

The other option is to create a category on UIViewController and do some swizzeling to intercept the viewDidLoad call and perform the automatic translation. However this is also quite agressive..

**Comment by pablosproject** [comment]
I would say that the second one (swizzling) is the most aggressive of the two 😁

**Pull request merged**
